INSERT INTO public.pergunta(
	id_pergunta,alternativa_a, alternativa_b,alternativa_c,alternativa_correta, alternativa_d, questao)
VALUES(1,'C. S. Lewis','Lewis Carroll','J.R.R. Tolkien','b','William Shakespeare','Quem é o autor de Alice no País das Maravilhas?'),
(2,'Alexandre Dumas','Julio Cortázar','Jostein Gaarder','a','Miguel de Cervantes','Quem é o autor de Os Três Mosqueteiros?'),
(3,'Friedrich Niezsche','Fiódor Dostoiévski','Franz Kafka','c','Victor Hugo','Quem é o autor de “Metamorfose”?'),
(4,'Victor Hugo','Gabriel Garcia Márquez','Machado de Assis','a','Julio Cortázar','Quem é o autor de “Os Miseráveis”? '),
(5,'Frank Baum','Herman Melville','Oscar Wilde','d','Dan Brown','Quem é o autor de “O Código da Vinci”? '),
(6,'Douglas Adams','Isaac Asimov','Arthur C. Clarke','d','Aldous Huxley','Quem é o autor de “Admirável Mundo Novo”?'),
(7,'Fiódor Dostoiévski','Franz Kafka','Oscar Wilde','a','Anton Tchekhov','Quem é o autor de “Crime e Castigo”? '),
(8,'Alexandre Dumas ','Ernest Hemingway','Nathaniel Hawthorne','d','Herman Melville','Quem é o autor de “Moby Dick”? '),
(9,'José de Alencar ','Machado de Assis','Joaquim Manuel de Macedo','d','Manuel Antônio de Almeida','Quem é o autor de “Memórias de um Sargento de Milícias”? '),
(10,'Herzog Ernst','Fiódor Dostoiévski','Ottfried von Weissenburg','d','Friedrich Nietzsche','Quem é o autor de “O Anticristo”? '),
(11,'Vira-tempo, Capa da Invisibilidade e Lembrol.','Capa da Invisibilidade, Varinha das Varinhas e Pedra da Ressurreição.','Cálice de Fogo, Pedra da Ressurreição e Horcrux.','b','Varinha das Varinhas, Horcrux e Lembrol.','Quais são os três itens mágicos da série Harry Potter que são conhecidos como Relíquias da Morte? '),
(12,'Titanic','Star Wars: O Despertar da Força','Avatar','c','Jurassic World','Qual o filme detentor do título de maior bilheteria?'),
(13,'8','5','10','c','6','Friends é uma série americana que foi transmitida de 1994 à 2004, possuindo 236 episódios. Quantas temporadas essa famosa série possui?'),
(14,'Homem-Aranha e Ciclope','Mulher Maravilha e Magneto','Robin e Estelar','a','Batman e Homem de Ferro','São heróis pertencentes a Marvel os seguintes personagens:'),
(15,'Quinhentismo','Romantismo','Realismo','d','Barroco','Qual foi a segunda escola literária do Brasil?'),
(16,'Peri','Ceci','Romeu','a','Rui','Qual o nome do protagonista masculino da obra O Guarani, de José de Alencar?'),
(17,'Proust','Mendeleev','Robespierre','d','Lavoisier','Quem é conhecido como o pai da química?'),
(18,'Ou','Au','Ag','b','Or','Como o ouro aparece na tela periódica?'),
(19,'Narcos','13 Reasons Why','3%','c','Marco Polo','Após embarcar em terras brasileiras, a Netflix anunciou a produção de uma série totalmente rodada aqui. Qual é o título desse drama distópico?'),
(20,'Budismo','Judaísmo','Catolicismo','d','Protestantismo','Qual é a maior religião dos Estados Unidos?'),
(21,'Cristo Redentor','Taj Mahal','Coliseu Romano','d','Farol de Alexandria','Qual dos elementos citados abaixo não faz parte das Sete Maravilhas do Mundo Moderno? '),
(22,'Segunda Guerra Mundial','Revolução Francesa','Guerra Fria','d','Revolução Russa','Qual importante evento da história as ideias iluministas influenciaram?'),
(23,'Mãos vazias','Derrubar','Costas no chão','d','Caminho da Suavidade','O que significa judô? '),
(24,'Nato','Corporativo','Serial','c','Social','Qual o empreendedor que cria a ideia e vende para iniciar outras ideias? '),
(25,'Rússia, França e Brasil','Inglaterra, Rússia e França','Espanha, Colômbia e Inglaterra','b','França, Espanha e Peru','Em que países o Balé mais se desenvolveu? '),
(26,'Porque apresentam fusão a 23','Porque perdem elétrons','Porque seus elétrons são livre','c','Porque seus elétrons mantêm-se em um único lugar',' Por que os metais apresentam alta condutividade elétrica?'),
(27,'Carnivores Tour','Disaster Tour','The Hunting Party Tour','a','Brutal Tour',' A Turnê feita com as bandas Linking Park e Thirty Seconds to Mars chama-se:'),
(28,'José Raul Capaclanca','Alexander Alekhine','Garry Kasparov','d','Wilhelm Steinitz','Quem foi o primeiro campeão de xadrez do mundo?'),
(29,'Apolo','Ares','Dioniso','c','Hermes','Qual o nome do deus do vinho na mitologia grega? '),
(30,'Montanha Sombria','Montanha da Névoa','Condado','d','Erebor','No filme “Hobbit”, qual o nome da montanha a qual Smaug dominou?');
